### ISSUE TITLE
LiveUpdateParams is missing form tag

### ISSUE THREAD

**Issue by hiepvv** [uizaio/api-wrapper-go#100]
When i used api update live event, i had got this message: `{\"code\":422,\"message\":\"Parameters validation error!\",\"DescriptionLink\":\"https://docs.uiza.io/#errors-code\"}"`.
It means i'm missing some params is required but not. So i've checked LiveUpdateParams struct and notice that this struct is missing form tag, lead to my request is failed.
Please check this issue. Thanks.

**Comment by LeTanThanh** [comment]
@hiepvv we released version 1.2.2 on [PR#102](https://github.com/uizaio/api-wrapper-go/pull/103), please help me check thí issue on this version

**Comment by hiepvv** [comment]
hi @LeTanThanh, it works. thanks a lot.
