### ISSUE TITLE
Type of LastPushInfo in LiveData struct is not correct 

### ISSUE THREAD

**Issue by hiepvv** [uizaio/api-wrapper-go#96]
In v4 document, lastPushInfo is declared as a array, but in LiveData struct, it is a string type. It makes streamUrl and streamKey be invisible and can not get it by any way, please fix it.

Thanks.

**Comment by LeTanThanh** [comment]
@hiepvv thanks for you report issue. We fixed it in [PR#97](https://github.com/uizaio/api-wrapper-go/pull/97/files) anh release version 1.2.1, please help me check again

**Comment by hiepvv** [comment]
thanks @LeTanThanh, excellent work.
